server:
    port: 8090
javax:
    sql:
        DataSource:
            developerDataSource:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:mem:developer;INIT=RUNSCRIPT FROM 'classpath:developer.ddl' 
                    user: sa
                    password: ""