CREATE TABLE IF NOT EXISTS DEVELOPER (
    ID VARCHAR(64) NOT NULL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    TEAM VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE
);

MERGE INTO DEVELOPER (ID, NAME, TEAM) VALUES ('15514f37-05c4-4b27-a9c1-7bf6de8823a4', 'Sean', 'DPE');