CREATE TABLE IF NOT EXISTS DEVELOPER (
    ID VARCHAR(64) NOT NULL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    TEAM VARCHAR(64) NOT NULL,
    SKILLS VARCHAR(200),
    CREATED_AT TIMESTAMP WITH TIME ZONE,
    UPDATED_AT TIMESTAMP WITH TIME ZONE
);

MERGE INTO DEVELOPER (ID, NAME, TEAM, SKILLS) VALUES ('15514f37-05c4-4b27-a9c1-7bf6de8823a4', 'Sean', 'DPE', 'Java,C#,Mule');